//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder
    {
        public int foodOrderId { get; set; }
        public string foodOrderName { get; set; }
        public int foodOrderQuantity { get; set; }
        public double foodOrderPrice { get; set; }
    }
}
